{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nbviewer.fullname" . }}
  labels:
    {{- include "nbviewer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "nbviewer.matchLabels" . | nindent 6 }}
{{- end }}
